use std::hash::{Hash, Hasher};
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

const DEFAULT_INSTANCE_NAME: &str = "omenbrowser_rs";
const INSTANCE_NAME_PREFIX: &str = "omenbrowser_rs_";
const DEFAULT_CONFIG_HEADER: &str = "# OMENbrowser_rs managed Reticulum configuration
# Generated by the OMENbrowser_rs Interfaces panel.

[reticulum]
share_instance = Yes
instance_name = omenbrowser_rs
enable_transport = No

[logging]
loglevel = 4

[interfaces]";

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum InterfaceKind {
    Auto,
    TcpClient,
    TcpServer,
    I2p,
    RNode,
    Unknown(String),
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ReticulumInterfaceProfile {
    pub profile_id: String,
    pub name: String,
    pub kind: InterfaceKind,
    pub enabled: bool,
    pub target_host: String,
    pub target_port: u16,
    pub network_name: String,
    pub passphrase: String,
    pub connectable: bool,
    pub peers: Vec<String>,
    pub device_port: String,
    pub frequency: u64,
    pub bandwidth: u64,
    pub tx_power: i32,
    pub spreading_factor: u8,
    pub coding_rate: u8,
}

impl ReticulumInterfaceProfile {
    pub fn auto(profile_id: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            profile_id: profile_id.into(),
            name: name.into(),
            kind: InterfaceKind::Auto,
            enabled: true,
            target_host: String::new(),
            target_port: 4242,
            network_name: String::new(),
            passphrase: String::new(),
            connectable: false,
            peers: Vec::new(),
            device_port: String::new(),
            frequency: 867_200_000,
            bandwidth: 125_000,
            tx_power: 7,
            spreading_factor: 8,
            coding_rate: 5,
        }
    }

    pub fn tcp_client(profile_id: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            profile_id: profile_id.into(),
            name: name.into(),
            kind: InterfaceKind::TcpClient,
            enabled: true,
            target_host: String::new(),
            target_port: 4242,
            network_name: String::new(),
            passphrase: String::new(),
            connectable: false,
            peers: Vec::new(),
            device_port: String::new(),
            frequency: 867_200_000,
            bandwidth: 125_000,
            tx_power: 7,
            spreading_factor: 8,
            coding_rate: 5,
        }
    }

    pub fn tcp_server(profile_id: impl Into<String>, name: impl Into<String>) -> Self {
        let mut profile = Self::tcp_client(profile_id, name);
        profile.kind = InterfaceKind::TcpServer;
        profile.target_host = "0.0.0.0".into();
        profile
    }

    pub fn i2p(profile_id: impl Into<String>, name: impl Into<String>) -> Self {
        let mut profile = Self::tcp_client(profile_id, name);
        profile.kind = InterfaceKind::I2p;
        profile.connectable = true;
        profile
    }

    pub fn rnode(profile_id: impl Into<String>, name: impl Into<String>) -> Self {
        let mut profile = Self::tcp_client(profile_id, name);
        profile.kind = InterfaceKind::RNode;
        profile
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct GatewayPreset {
    pub id: String,
    pub name: String,
    pub host: String,
    pub port: u16,
}

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
struct InterfaceProfilesFile {
    profiles: Vec<ReticulumInterfaceProfile>,
}

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
struct GatewayPresetsFile {
    gateways: Vec<GatewayPreset>,
}

#[derive(Clone, Debug)]
pub struct InterfaceConfigService {
    profiles_path: PathBuf,
    reticulum_config_dir: PathBuf,
    config_path: PathBuf,
    gateways_path: PathBuf,
    profiles: Vec<ReticulumInterfaceProfile>,
}

impl InterfaceConfigService {
    pub fn new(
        profiles_path: PathBuf,
        reticulum_config_dir: PathBuf,
        gateways_path: PathBuf,
    ) -> crate::error::AppResult<Self> {
        let config_path = reticulum_config_dir.join("config");
        let mut service = Self {
            profiles_path,
            reticulum_config_dir,
            config_path,
            gateways_path,
            profiles: Vec::new(),
        };
        service.ensure_gateway_presets()?;
        service.profiles = service.load_profiles()?;
        if service.profiles.is_empty() {
            service.profiles = vec![ReticulumInterfaceProfile::auto(
                new_profile_id(),
                "Default Interface",
            )];
            service.persist()?;
        }
        service.apply()?;
        Ok(service)
    }

    pub fn list_profiles(&self) -> &[ReticulumInterfaceProfile] {
        &self.profiles
    }

    pub fn get(&self, profile_id: &str) -> Option<&ReticulumInterfaceProfile> {
        self.profiles
            .iter()
            .find(|profile| profile.profile_id == profile_id)
    }

    pub fn create(
        &mut self,
        kind: InterfaceKind,
    ) -> crate::error::AppResult<ReticulumInterfaceProfile> {
        let profile = match kind {
            InterfaceKind::Auto => {
                ReticulumInterfaceProfile::auto(unique_profile_id(&self.profiles), "Auto Interface")
            }
            InterfaceKind::TcpClient => ReticulumInterfaceProfile::tcp_client(
                unique_profile_id(&self.profiles),
                "TCP Gateway",
            ),
            InterfaceKind::TcpServer => ReticulumInterfaceProfile::tcp_server(
                unique_profile_id(&self.profiles),
                "TCP Server",
            ),
            InterfaceKind::I2p => {
                ReticulumInterfaceProfile::i2p(unique_profile_id(&self.profiles), "I2P")
            }
            InterfaceKind::RNode => {
                ReticulumInterfaceProfile::rnode(unique_profile_id(&self.profiles), "RNode")
            }
            InterfaceKind::Unknown(kind) => ReticulumInterfaceProfile {
                kind: InterfaceKind::Unknown(kind),
                ..ReticulumInterfaceProfile::auto(
                    unique_profile_id(&self.profiles),
                    "Unknown Interface",
                )
            },
        };
        self.profiles.insert(0, profile.clone());
        self.persist()?;
        Ok(profile)
    }

    pub fn update(&mut self, profile: ReticulumInterfaceProfile) -> crate::error::AppResult<bool> {
        let Some(existing) = self
            .profiles
            .iter_mut()
            .find(|item| item.profile_id == profile.profile_id)
        else {
            return Ok(false);
        };
        *existing = profile;
        self.persist()?;
        Ok(true)
    }

    pub fn toggle_enabled(
        &mut self,
        profile_id: &str,
    ) -> crate::error::AppResult<Option<ReticulumInterfaceProfile>> {
        let Some(profile) = self
            .profiles
            .iter_mut()
            .find(|profile| profile.profile_id == profile_id)
        else {
            return Ok(None);
        };
        profile.enabled = !profile.enabled;
        let profile = profile.clone();
        self.persist()?;
        Ok(Some(profile))
    }

    pub fn toggle_connectable(
        &mut self,
        profile_id: &str,
    ) -> crate::error::AppResult<Option<ReticulumInterfaceProfile>> {
        let Some(profile) = self
            .profiles
            .iter_mut()
            .find(|profile| profile.profile_id == profile_id)
        else {
            return Ok(None);
        };
        if profile.kind == InterfaceKind::I2p {
            profile.connectable = !profile.connectable;
        }
        let profile = profile.clone();
        self.persist()?;
        Ok(Some(profile))
    }

    pub fn delete(&mut self, profile_id: &str) -> crate::error::AppResult<bool> {
        let before = self.profiles.len();
        self.profiles
            .retain(|profile| profile.profile_id != profile_id);
        let changed = self.profiles.len() != before;
        if changed {
            self.persist()?;
        }
        Ok(changed)
    }

    pub fn apply(&self) -> crate::error::AppResult<PathBuf> {
        std::fs::create_dir_all(&self.reticulum_config_dir)?;
        let rendered = self.render_config_for_apply();
        write_atomic(&self.config_path, rendered.as_bytes())?;
        Ok(self.config_path.clone())
    }

    pub fn render_config(&self) -> String {
        let instance_name = std::fs::read_to_string(&self.config_path)
            .ok()
            .and_then(|existing| read_reticulum_value(&existing, "instance_name"))
            .unwrap_or_else(new_instance_name);
        render_config_with_instance_name(&self.profiles, &instance_name)
    }

    pub fn render_config_for_apply(&self) -> String {
        let existing = std::fs::read_to_string(&self.config_path).ok();
        let instance_name = existing
            .as_deref()
            .and_then(|config| read_reticulum_value(config, "instance_name"))
            .unwrap_or_else(new_instance_name);
        let rendered = render_config_with_instance_name(&self.profiles, &instance_name);
        let Ok(existing) = std::fs::read_to_string(&self.config_path) else {
            return rendered;
        };
        let Some(identity) = read_reticulum_value(&existing, "network_identity") else {
            return rendered;
        };
        render_config_with_network_identity(&rendered, &identity)
    }

    pub fn config_path(&self) -> &PathBuf {
        &self.config_path
    }

    pub fn gateway_presets(&self) -> crate::error::AppResult<Vec<GatewayPreset>> {
        let raw = std::fs::read_to_string(&self.gateways_path)?;
        let payload: GatewayPresetsFile = serde_json::from_str(&raw)
            .map_err(|err| crate::error::AppError::Settings(err.to_string()))?;
        Ok(payload.gateways)
    }

    pub fn create_gateway_profile(
        &mut self,
        gateway_id: &str,
    ) -> crate::error::AppResult<Option<ReticulumInterfaceProfile>> {
        let Some(preset) = self
            .gateway_presets()?
            .into_iter()
            .find(|preset| preset.id == gateway_id)
        else {
            return Ok(None);
        };
        let mut profile =
            ReticulumInterfaceProfile::tcp_client(unique_profile_id(&self.profiles), preset.name);
        profile.target_host = preset.host;
        profile.target_port = preset.port;
        self.profiles.insert(0, profile.clone());
        self.persist()?;
        Ok(Some(profile))
    }

    fn load_profiles(&self) -> crate::error::AppResult<Vec<ReticulumInterfaceProfile>> {
        if !self.profiles_path.exists() {
            return Ok(Vec::new());
        }
        let raw = std::fs::read_to_string(&self.profiles_path)?;
        let payload: InterfaceProfilesFile = serde_json::from_str(&raw)
            .map_err(|err| crate::error::AppError::Settings(err.to_string()))?;
        Ok(payload.profiles)
    }

    fn persist(&self) -> crate::error::AppResult<()> {
        if let Some(parent) = self.profiles_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let payload = InterfaceProfilesFile {
            profiles: self.profiles.clone(),
        };
        std::fs::write(
            &self.profiles_path,
            serde_json::to_vec_pretty(&payload).expect("profiles serialize"),
        )?;
        Ok(())
    }

    fn ensure_gateway_presets(&self) -> crate::error::AppResult<()> {
        if self.gateways_path.exists() {
            return Ok(());
        }
        if let Some(legacy_path) = legacy_gateways_path(&self.gateways_path) {
            if legacy_path.exists() {
                if let Some(parent) = self.gateways_path.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::copy(&legacy_path, &self.gateways_path)?;
                return Ok(());
            }
        }
        if let Some(parent) = self.gateways_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let payload = GatewayPresetsFile {
            gateways: vec![
                GatewayPreset {
                    id: "rmap".into(),
                    name: "RMAP".into(),
                    host: "rmap.world".into(),
                    port: 4242,
                },
                GatewayPreset {
                    id: "wns".into(),
                    name: "WNS".into(),
                    host: "107.175.67.46".into(),
                    port: 4242,
                },
            ],
        };
        std::fs::write(
            &self.gateways_path,
            serde_json::to_vec_pretty(&payload).expect("gateways serialize"),
        )?;
        Ok(())
    }
}

fn legacy_gateways_path(path: &std::path::Path) -> Option<PathBuf> {
    let file_name = path.file_name()?.to_str()?;
    if file_name != "interface_gateways.json" {
        return None;
    }
    Some(path.with_file_name("gateways.json"))
}

pub fn render_config(profiles: &[ReticulumInterfaceProfile]) -> String {
    render_config_with_instance_name(profiles, DEFAULT_INSTANCE_NAME)
}

pub fn render_config_with_instance_name(
    profiles: &[ReticulumInterfaceProfile],
    instance_name: &str,
) -> String {
    let safe_instance_name = safe_instance_name(instance_name);
    let mut lines = vec![DEFAULT_CONFIG_HEADER.replace(
        "instance_name = omenbrowser_rs",
        &format!("instance_name = {safe_instance_name}"),
    )];
    let mut used_section_names = Vec::new();
    for profile in profiles {
        let section_name = unique_section_name(profile, &used_section_names);
        used_section_names.push(section_name.clone());
        lines.extend(render_profile(profile, &section_name));
        lines.push(String::new());
    }
    format!("{}\n", lines.join("\n").trim_end())
}

fn render_profile(profile: &ReticulumInterfaceProfile, section_name: &str) -> Vec<String> {
    let enabled = if profile.enabled { "Yes" } else { "No" };
    let interface_enabled = if profile.enabled { "true" } else { "false" };
    let mut lines = vec![format!("  [[{}]]", section_name)];
    match &profile.kind {
        InterfaceKind::Auto => {
            lines.push("    type = AutoInterface".into());
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
        }
        InterfaceKind::TcpClient => {
            lines.push("    type = TCPClientInterface".into());
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
            lines.push(format!(
                "    target_host = {}",
                if profile.target_host.is_empty() {
                    "127.0.0.1"
                } else {
                    &profile.target_host
                }
            ));
            lines.push(format!("    target_port = {}", profile.target_port));
            if !profile.network_name.is_empty() {
                lines.push(format!("    network_name = {}", profile.network_name));
            }
            if !profile.passphrase.is_empty() {
                lines.push(format!("    passphrase = {}", profile.passphrase));
            }
        }
        InterfaceKind::TcpServer => {
            lines.push("    type = TCPServerInterface".into());
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
            lines.push(format!(
                "    listen_ip = {}",
                if profile.target_host.is_empty() {
                    "0.0.0.0"
                } else {
                    &profile.target_host
                }
            ));
            lines.push(format!("    listen_port = {}", profile.target_port));
            if !profile.network_name.is_empty() {
                lines.push(format!("    network_name = {}", profile.network_name));
            }
            if !profile.passphrase.is_empty() {
                lines.push(format!("    passphrase = {}", profile.passphrase));
            }
        }
        InterfaceKind::I2p => {
            lines.push("    type = I2PInterface".into());
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
            lines.push(format!(
                "    connectable = {}",
                if profile.connectable { "Yes" } else { "No" }
            ));
            lines.push(format!("    peers = {}", profile.peers.join(", ")));
        }
        InterfaceKind::RNode => {
            lines.push("    type = RNodeInterface".into());
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
            lines.push(format!("    port = {}", profile.device_port));
            lines.push(format!("    frequency = {}", profile.frequency));
            lines.push(format!("    bandwidth = {}", profile.bandwidth));
            lines.push(format!("    txpower = {}", profile.tx_power));
            lines.push(format!(
                "    spreadingfactor = {}",
                profile.spreading_factor
            ));
            lines.push(format!("    codingrate = {}", profile.coding_rate));
        }
        InterfaceKind::Unknown(kind) => {
            lines.push(format!("    type = {kind}"));
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
        }
    }
    lines
}

fn unique_section_name(profile: &ReticulumInterfaceProfile, used: &[String]) -> String {
    let base = if profile.name.trim().is_empty() {
        profile.profile_id.as_str()
    } else {
        profile.name.trim()
    };
    if !used.iter().any(|name| name == base) {
        return base.to_string();
    }

    let mut candidate = format!("{base} {}", profile.profile_id);
    if !used.iter().any(|name| name == &candidate) {
        return candidate;
    }

    for suffix in 2.. {
        candidate = format!("{base} {suffix}");
        if !used.iter().any(|name| name == &candidate) {
            return candidate;
        }
    }
    unreachable!("unbounded suffix search always returns")
}

fn render_config_with_network_identity(config: &str, identity: &str) -> String {
    let identity_line = format!("network_identity = {identity}");
    let mut output = Vec::new();
    let mut in_reticulum = false;
    let mut inserted = false;

    for line in config.lines() {
        let trimmed = line.trim();
        let starts_section = trimmed.starts_with('[') && trimmed.ends_with(']');
        if starts_section {
            if in_reticulum && !inserted {
                output.push(identity_line.clone());
                inserted = true;
            }
            in_reticulum = trimmed == "[reticulum]";
        }

        if in_reticulum && trimmed.starts_with("network_identity") {
            if !inserted {
                output.push(identity_line.clone());
                inserted = true;
            }
            continue;
        }
        output.push(line.to_string());
    }

    if in_reticulum && !inserted {
        output.push(identity_line);
    }

    format!("{}\n", output.join("\n").trim_end())
}

fn read_reticulum_value(config: &str, expected_key: &str) -> Option<String> {
    let mut in_reticulum = false;
    for line in config.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            in_reticulum = trimmed == "[reticulum]";
            continue;
        }
        if !in_reticulum {
            continue;
        }
        let Some((key, value)) = trimmed.split_once('=') else {
            continue;
        };
        if key.trim() == expected_key {
            let value = value.trim();
            if !value.is_empty() {
                return Some(value.to_string());
            }
        }
    }
    None
}

fn safe_instance_name(value: &str) -> String {
    let sanitized = value
        .trim()
        .chars()
        .filter(|ch| ch.is_ascii_alphanumeric() || *ch == '_' || *ch == '-')
        .collect::<String>();
    if sanitized.is_empty() {
        DEFAULT_INSTANCE_NAME.into()
    } else {
        sanitized
    }
}

fn new_instance_name() -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::sync::atomic::{AtomicU64, Ordering};
    use std::time::{SystemTime, UNIX_EPOCH};

    static COUNTER: AtomicU64 = AtomicU64::new(0);

    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let counter = COUNTER.fetch_add(1, Ordering::Relaxed);
    let mut hasher = DefaultHasher::new();
    nanos.hash(&mut hasher);
    std::process::id().hash(&mut hasher);
    counter.hash(&mut hasher);
    format!(
        "{INSTANCE_NAME_PREFIX}{:06x}",
        hasher.finish() & 0x00ff_ffff
    )
}

fn write_atomic(path: &std::path::Path, bytes: &[u8]) -> crate::error::AppResult<()> {
    let tmp_path = path.with_extension(format!("tmp-{}", std::process::id()));
    std::fs::write(&tmp_path, bytes)?;
    if let Err(error) = std::fs::rename(&tmp_path, path) {
        let _ = std::fs::remove_file(&tmp_path);
        return Err(error.into());
    }
    Ok(())
}

fn new_profile_id() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let millis = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();
    format!("iface_{millis:x}")
}

fn unique_profile_id(existing: &[ReticulumInterfaceProfile]) -> String {
    let base = new_profile_id();
    if !existing.iter().any(|profile| profile.profile_id == base) {
        return base;
    }
    for suffix in 1.. {
        let candidate = format!("{base}_{suffix}");
        if !existing
            .iter()
            .any(|profile| profile.profile_id == candidate)
        {
            return candidate;
        }
    }
    unreachable!("unbounded suffix search always returns")
}
