use std::fs::{File, OpenOptions};
use std::hash::{Hash, Hasher};
use std::io::{ErrorKind, Read, Write};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use serde::{Deserialize, Serialize};

use crate::error::{AppError, AppResult};
use crate::storage::files::atomic_replace;

const DEFAULT_INSTANCE_NAME: &str = "omenbrowser_rs";
const INSTANCE_NAME_PREFIX: &str = "omenbrowser_rs_";
pub const INTERFACE_PROFILES_MAX_BYTES: u64 = 2 * 1024 * 1024;
pub const INTERFACE_PROFILES_MAX_ITEMS: usize = 64;
pub const INTERFACE_PROFILE_MAX_PEERS: usize = 64;
pub const INTERFACE_PROFILE_MAX_FIELD_BYTES: usize = 16 * 1024;
pub const INTERFACE_PROFILE_MAX_PASSPHRASE_BYTES: usize = 4096;
pub const GATEWAY_PRESETS_MAX_BYTES: u64 = 1024 * 1024;
pub const GATEWAY_PRESETS_MAX_ITEMS: usize = 256;
pub const RETICULUM_CONFIG_MAX_BYTES: u64 = 1024 * 1024;
static INTERFACE_FILE_SEQUENCE: AtomicU64 = AtomicU64::new(1);
const DEFAULT_CONFIG_HEADER: &str = "# OMENbrowser_rs managed Reticulum configuration
# Generated by the OMENbrowser_rs Interfaces panel.

[reticulum]
share_instance = Yes
instance_name = omenbrowser_rs
enable_transport = No

[logging]
loglevel = 4

[interfaces]";

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum InterfaceKind {
    Auto,
    TcpClient,
    TcpServer,
    I2p,
    RNode,
    Unknown(String),
}

#[derive(Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ReticulumInterfaceProfile {
    pub profile_id: String,
    pub name: String,
    pub kind: InterfaceKind,
    pub enabled: bool,
    pub target_host: String,
    pub target_port: u16,
    pub network_name: String,
    pub passphrase: String,
    pub connectable: bool,
    pub peers: Vec<String>,
    pub device_port: String,
    pub frequency: u64,
    pub bandwidth: u64,
    pub tx_power: i32,
    pub spreading_factor: u8,
    pub coding_rate: u8,
}

impl std::fmt::Debug for ReticulumInterfaceProfile {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ReticulumInterfaceProfile")
            .field("profile_id", &self.profile_id)
            .field("name", &self.name)
            .field("kind", &self.kind)
            .field("enabled", &self.enabled)
            .field("target_host", &self.target_host)
            .field("target_port", &self.target_port)
            .field("network_name", &self.network_name)
            .field(
                "passphrase",
                &(!self.passphrase.is_empty()).then_some("<redacted>"),
            )
            .field("connectable", &self.connectable)
            .field("peers", &self.peers)
            .field("device_port", &self.device_port)
            .field("frequency", &self.frequency)
            .field("bandwidth", &self.bandwidth)
            .field("tx_power", &self.tx_power)
            .field("spreading_factor", &self.spreading_factor)
            .field("coding_rate", &self.coding_rate)
            .finish()
    }
}

impl ReticulumInterfaceProfile {
    pub fn auto(profile_id: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            profile_id: profile_id.into(),
            name: name.into(),
            kind: InterfaceKind::Auto,
            enabled: true,
            target_host: String::new(),
            target_port: 4242,
            network_name: String::new(),
            passphrase: String::new(),
            connectable: false,
            peers: Vec::new(),
            device_port: String::new(),
            frequency: 867_200_000,
            bandwidth: 125_000,
            tx_power: 7,
            spreading_factor: 8,
            coding_rate: 5,
        }
    }

    pub fn tcp_client(profile_id: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            profile_id: profile_id.into(),
            name: name.into(),
            kind: InterfaceKind::TcpClient,
            enabled: true,
            target_host: String::new(),
            target_port: 4242,
            network_name: String::new(),
            passphrase: String::new(),
            connectable: false,
            peers: Vec::new(),
            device_port: String::new(),
            frequency: 867_200_000,
            bandwidth: 125_000,
            tx_power: 7,
            spreading_factor: 8,
            coding_rate: 5,
        }
    }

    pub fn tcp_server(profile_id: impl Into<String>, name: impl Into<String>) -> Self {
        let mut profile = Self::tcp_client(profile_id, name);
        profile.kind = InterfaceKind::TcpServer;
        profile.target_host = "0.0.0.0".into();
        profile
    }

    pub fn i2p(profile_id: impl Into<String>, name: impl Into<String>) -> Self {
        let mut profile = Self::tcp_client(profile_id, name);
        profile.kind = InterfaceKind::I2p;
        profile.connectable = true;
        profile
    }

    pub fn rnode(profile_id: impl Into<String>, name: impl Into<String>) -> Self {
        let mut profile = Self::tcp_client(profile_id, name);
        profile.kind = InterfaceKind::RNode;
        profile
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct GatewayPreset {
    pub id: String,
    pub name: String,
    pub host: String,
    pub port: u16,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum GatewayProfileCreateOutcome {
    Created(ReticulumInterfaceProfile),
    Enabled(ReticulumInterfaceProfile),
    AlreadyEnabled(ReticulumInterfaceProfile),
}

impl GatewayProfileCreateOutcome {
    pub fn profile(&self) -> &ReticulumInterfaceProfile {
        match self {
            Self::Created(profile) | Self::Enabled(profile) | Self::AlreadyEnabled(profile) => {
                profile
            }
        }
    }
}

impl std::ops::Deref for GatewayProfileCreateOutcome {
    type Target = ReticulumInterfaceProfile;

    fn deref(&self) -> &Self::Target {
        self.profile()
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
struct InterfaceProfilesFile {
    profiles: Vec<ReticulumInterfaceProfile>,
}

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
struct GatewayPresetsFile {
    gateways: Vec<GatewayPreset>,
}

#[derive(Clone, Debug)]
pub struct InterfaceConfigService {
    profiles_path: PathBuf,
    reticulum_config_dir: PathBuf,
    config_path: PathBuf,
    gateways_path: PathBuf,
    profiles: Vec<ReticulumInterfaceProfile>,
}

impl InterfaceConfigService {
    pub fn new(
        profiles_path: PathBuf,
        reticulum_config_dir: PathBuf,
        gateways_path: PathBuf,
    ) -> crate::error::AppResult<Self> {
        let config_path = reticulum_config_dir.join("config");
        let mut service = Self {
            profiles_path,
            reticulum_config_dir,
            config_path,
            gateways_path,
            profiles: Vec::new(),
        };
        service.ensure_gateway_presets()?;
        service.profiles = service.load_profiles()?;
        if service.profiles.is_empty() {
            service.profiles = vec![ReticulumInterfaceProfile::auto(
                new_profile_id(),
                "Default Interface",
            )];
            service.persist()?;
        }
        service.apply()?;
        Ok(service)
    }

    pub fn list_profiles(&self) -> &[ReticulumInterfaceProfile] {
        &self.profiles
    }

    pub fn get(&self, profile_id: &str) -> Option<&ReticulumInterfaceProfile> {
        self.profiles
            .iter()
            .find(|profile| profile.profile_id == profile_id)
    }

    pub fn create(
        &mut self,
        kind: InterfaceKind,
    ) -> crate::error::AppResult<ReticulumInterfaceProfile> {
        let previous = self.profiles.clone();
        let profile = match kind {
            InterfaceKind::Auto => {
                ReticulumInterfaceProfile::auto(unique_profile_id(&self.profiles), "Auto Interface")
            }
            InterfaceKind::TcpClient => ReticulumInterfaceProfile::tcp_client(
                unique_profile_id(&self.profiles),
                "TCP Gateway",
            ),
            InterfaceKind::TcpServer => ReticulumInterfaceProfile::tcp_server(
                unique_profile_id(&self.profiles),
                "TCP Server",
            ),
            InterfaceKind::I2p => {
                ReticulumInterfaceProfile::i2p(unique_profile_id(&self.profiles), "I2P")
            }
            InterfaceKind::RNode => {
                ReticulumInterfaceProfile::rnode(unique_profile_id(&self.profiles), "RNode")
            }
            InterfaceKind::Unknown(kind) => ReticulumInterfaceProfile {
                kind: InterfaceKind::Unknown(kind),
                ..ReticulumInterfaceProfile::auto(
                    unique_profile_id(&self.profiles),
                    "Unknown Interface",
                )
            },
        };
        self.profiles.insert(0, profile.clone());
        if let Err(error) = self.persist() {
            self.profiles = previous;
            return Err(error);
        }
        Ok(profile)
    }

    pub fn update(&mut self, profile: ReticulumInterfaceProfile) -> crate::error::AppResult<bool> {
        let Some(index) = self
            .profiles
            .iter()
            .position(|item| item.profile_id == profile.profile_id)
        else {
            return Ok(false);
        };
        validate_interface_profile(&profile)?;
        let previous = self.profiles.clone();
        self.profiles[index] = profile;
        if let Err(error) = self.persist() {
            self.profiles = previous;
            return Err(error);
        }
        Ok(true)
    }

    pub fn toggle_enabled(
        &mut self,
        profile_id: &str,
    ) -> crate::error::AppResult<Option<ReticulumInterfaceProfile>> {
        let previous = self.profiles.clone();
        let Some(profile) = self
            .profiles
            .iter_mut()
            .find(|profile| profile.profile_id == profile_id)
        else {
            return Ok(None);
        };
        profile.enabled = !profile.enabled;
        let profile = profile.clone();
        if let Err(error) = self.persist() {
            self.profiles = previous;
            return Err(error);
        }
        Ok(Some(profile))
    }

    pub fn toggle_connectable(
        &mut self,
        profile_id: &str,
    ) -> crate::error::AppResult<Option<ReticulumInterfaceProfile>> {
        let previous = self.profiles.clone();
        let Some(profile) = self
            .profiles
            .iter_mut()
            .find(|profile| profile.profile_id == profile_id)
        else {
            return Ok(None);
        };
        if profile.kind == InterfaceKind::I2p {
            profile.connectable = !profile.connectable;
        }
        let profile = profile.clone();
        if let Err(error) = self.persist() {
            self.profiles = previous;
            return Err(error);
        }
        Ok(Some(profile))
    }

    pub fn delete(&mut self, profile_id: &str) -> crate::error::AppResult<bool> {
        let previous = self.profiles.clone();
        let before = self.profiles.len();
        self.profiles
            .retain(|profile| profile.profile_id != profile_id);
        let changed = self.profiles.len() != before;
        if changed {
            if let Err(error) = self.persist() {
                self.profiles = previous;
                return Err(error);
            }
        }
        Ok(changed)
    }

    pub fn apply(&self) -> crate::error::AppResult<PathBuf> {
        std::fs::create_dir_all(&self.reticulum_config_dir)?;
        let rendered = self.try_render_config_for_apply()?;
        if rendered.len() as u64 > RETICULUM_CONFIG_MAX_BYTES {
            return Err(AppError::Settings(format!(
                "rendered Reticulum config exceeds the {RETICULUM_CONFIG_MAX_BYTES} byte limit"
            )));
        }
        write_atomic_private(&self.config_path, rendered.as_bytes())?;
        Ok(self.config_path.clone())
    }

    pub fn render_config(&self) -> String {
        let instance_name = read_bounded_utf8(&self.config_path, RETICULUM_CONFIG_MAX_BYTES)
            .ok()
            .flatten()
            .and_then(|existing| read_reticulum_value(&existing, "instance_name"))
            .unwrap_or_else(new_instance_name);
        render_config_with_instance_name(&self.profiles, &instance_name)
    }

    pub fn render_config_for_apply(&self) -> String {
        self.try_render_config_for_apply().unwrap_or_else(|_| {
            render_config_with_instance_name(&self.profiles, &new_instance_name())
        })
    }

    fn try_render_config_for_apply(&self) -> AppResult<String> {
        let existing = read_bounded_utf8(&self.config_path, RETICULUM_CONFIG_MAX_BYTES)?;
        let instance_name = existing
            .as_deref()
            .and_then(|config| read_reticulum_value(config, "instance_name"))
            .unwrap_or_else(new_instance_name);
        let rendered = render_config_with_instance_name(&self.profiles, &instance_name);
        let Some(existing) = existing else {
            return Ok(rendered);
        };
        let Some(identity) = read_reticulum_value(&existing, "network_identity") else {
            return Ok(rendered);
        };
        Ok(render_config_with_network_identity(&rendered, &identity))
    }

    pub fn config_path(&self) -> &PathBuf {
        &self.config_path
    }

    pub fn gateway_presets(&self) -> crate::error::AppResult<Vec<GatewayPreset>> {
        let raw = read_bounded_regular_file(&self.gateways_path, GATEWAY_PRESETS_MAX_BYTES)?
            .ok_or_else(|| AppError::Settings("gateway preset file is missing".into()))?;
        let payload: GatewayPresetsFile =
            serde_json::from_slice(&raw).map_err(|err| AppError::Settings(err.to_string()))?;
        validate_gateway_presets(&payload)?;
        Ok(payload.gateways)
    }

    pub fn create_gateway_profile(
        &mut self,
        gateway_id: &str,
    ) -> crate::error::AppResult<Option<GatewayProfileCreateOutcome>> {
        let Some(preset) = self
            .gateway_presets()?
            .into_iter()
            .find(|preset| preset.id == gateway_id)
        else {
            return Ok(None);
        };
        let previous = self.profiles.clone();
        if let Some(existing) = self.profiles.iter_mut().find(|profile| {
            profile.kind == InterfaceKind::TcpClient
                && profile.target_host == preset.host
                && profile.target_port == preset.port
        }) {
            if existing.enabled {
                return Ok(Some(GatewayProfileCreateOutcome::AlreadyEnabled(
                    existing.clone(),
                )));
            }
            existing.enabled = true;
            let profile = existing.clone();
            if let Err(error) = self.persist() {
                self.profiles = previous;
                return Err(error);
            }
            return Ok(Some(GatewayProfileCreateOutcome::Enabled(profile)));
        }
        let mut profile =
            ReticulumInterfaceProfile::tcp_client(unique_profile_id(&self.profiles), preset.name);
        profile.target_host = preset.host;
        profile.target_port = preset.port;
        self.profiles.insert(0, profile.clone());
        if let Err(error) = self.persist() {
            self.profiles = previous;
            return Err(error);
        }
        Ok(Some(GatewayProfileCreateOutcome::Created(profile)))
    }

    fn load_profiles(&self) -> crate::error::AppResult<Vec<ReticulumInterfaceProfile>> {
        let Some(raw) =
            read_bounded_regular_file(&self.profiles_path, INTERFACE_PROFILES_MAX_BYTES)?
        else {
            return Ok(Vec::new());
        };
        let payload: InterfaceProfilesFile =
            serde_json::from_slice(&raw).map_err(|err| AppError::Settings(err.to_string()))?;
        validate_interface_profiles(&payload)?;
        Ok(payload.profiles)
    }

    fn persist(&self) -> crate::error::AppResult<()> {
        if let Some(parent) = self.profiles_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let payload = InterfaceProfilesFile {
            profiles: self.profiles.clone(),
        };
        validate_interface_profiles(&payload)?;
        let mut raw = serde_json::to_vec_pretty(&payload)
            .map_err(|error| AppError::Settings(error.to_string()))?;
        raw.push(b'\n');
        if raw.len() as u64 > INTERFACE_PROFILES_MAX_BYTES {
            return Err(AppError::Settings(format!(
                "interface profiles exceed the {INTERFACE_PROFILES_MAX_BYTES} byte limit"
            )));
        }
        write_atomic_private(&self.profiles_path, &raw)?;
        Ok(())
    }

    fn ensure_gateway_presets(&self) -> crate::error::AppResult<()> {
        if let Some(raw) =
            read_bounded_regular_file(&self.gateways_path, GATEWAY_PRESETS_MAX_BYTES)?
        {
            let payload: GatewayPresetsFile = serde_json::from_slice(&raw)
                .map_err(|error| AppError::Settings(error.to_string()))?;
            validate_gateway_presets(&payload)?;
            return Ok(());
        }
        if let Some(legacy_path) = legacy_gateways_path(&self.gateways_path) {
            if let Some(raw) = read_bounded_regular_file(&legacy_path, GATEWAY_PRESETS_MAX_BYTES)? {
                let payload: GatewayPresetsFile = serde_json::from_slice(&raw)
                    .map_err(|error| AppError::Settings(error.to_string()))?;
                validate_gateway_presets(&payload)?;
                write_atomic_private(&self.gateways_path, &raw)?;
                return Ok(());
            }
        }
        if let Some(parent) = self.gateways_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let payload = GatewayPresetsFile {
            gateways: vec![
                GatewayPreset {
                    id: "rmap".into(),
                    name: "RMAP".into(),
                    host: "rmap.world".into(),
                    port: 4242,
                },
                GatewayPreset {
                    id: "wns".into(),
                    name: "WNS".into(),
                    host: "107.175.67.46".into(),
                    port: 4242,
                },
            ],
        };
        let mut raw = serde_json::to_vec_pretty(&payload)
            .map_err(|error| AppError::Settings(error.to_string()))?;
        raw.push(b'\n');
        write_atomic_private(&self.gateways_path, &raw)?;
        Ok(())
    }
}

fn legacy_gateways_path(path: &std::path::Path) -> Option<PathBuf> {
    let file_name = path.file_name()?.to_str()?;
    if file_name != "interface_gateways.json" {
        return None;
    }
    Some(path.with_file_name("gateways.json"))
}

pub fn render_config(profiles: &[ReticulumInterfaceProfile]) -> String {
    render_config_with_instance_name(profiles, DEFAULT_INSTANCE_NAME)
}

pub fn render_config_with_instance_name(
    profiles: &[ReticulumInterfaceProfile],
    instance_name: &str,
) -> String {
    let safe_instance_name = safe_instance_name(instance_name);
    let mut lines = vec![DEFAULT_CONFIG_HEADER.replace(
        "instance_name = omenbrowser_rs",
        &format!("instance_name = {safe_instance_name}"),
    )];
    let mut used_section_names = Vec::new();
    for profile in profiles {
        let section_name = unique_section_name(profile, &used_section_names);
        used_section_names.push(section_name.clone());
        lines.extend(render_profile(profile, &section_name));
        lines.push(String::new());
    }
    format!("{}\n", lines.join("\n").trim_end())
}

fn render_profile(profile: &ReticulumInterfaceProfile, section_name: &str) -> Vec<String> {
    let enabled = if profile.enabled { "Yes" } else { "No" };
    let interface_enabled = if profile.enabled { "true" } else { "false" };
    let mut lines = vec![format!("  [[{}]]", section_name)];
    match &profile.kind {
        InterfaceKind::Auto => {
            lines.push("    type = AutoInterface".into());
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
        }
        InterfaceKind::TcpClient => {
            lines.push("    type = TCPClientInterface".into());
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
            lines.push(format!(
                "    target_host = {}",
                if profile.target_host.is_empty() {
                    "127.0.0.1"
                } else {
                    &profile.target_host
                }
            ));
            lines.push(format!("    target_port = {}", profile.target_port));
            if !profile.network_name.is_empty() {
                lines.push(format!("    network_name = {}", profile.network_name));
            }
            if !profile.passphrase.is_empty() {
                lines.push(format!("    passphrase = {}", profile.passphrase));
            }
        }
        InterfaceKind::TcpServer => {
            lines.push("    type = TCPServerInterface".into());
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
            lines.push(format!(
                "    listen_ip = {}",
                if profile.target_host.is_empty() {
                    "0.0.0.0"
                } else {
                    &profile.target_host
                }
            ));
            lines.push(format!("    listen_port = {}", profile.target_port));
            if !profile.network_name.is_empty() {
                lines.push(format!("    network_name = {}", profile.network_name));
            }
            if !profile.passphrase.is_empty() {
                lines.push(format!("    passphrase = {}", profile.passphrase));
            }
        }
        InterfaceKind::I2p => {
            lines.push("    type = I2PInterface".into());
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
            lines.push(format!(
                "    connectable = {}",
                if profile.connectable { "Yes" } else { "No" }
            ));
            lines.push(format!("    peers = {}", profile.peers.join(", ")));
        }
        InterfaceKind::RNode => {
            lines.push("    type = RNodeInterface".into());
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
            lines.push(format!("    port = {}", profile.device_port));
            lines.push(format!("    frequency = {}", profile.frequency));
            lines.push(format!("    bandwidth = {}", profile.bandwidth));
            lines.push(format!("    txpower = {}", profile.tx_power));
            lines.push(format!(
                "    spreadingfactor = {}",
                profile.spreading_factor
            ));
            lines.push(format!("    codingrate = {}", profile.coding_rate));
        }
        InterfaceKind::Unknown(kind) => {
            lines.push(format!("    type = {kind}"));
            lines.push(format!("    enabled = {enabled}"));
            lines.push(format!("    interface_enabled = {interface_enabled}"));
        }
    }
    lines
}

fn unique_section_name(profile: &ReticulumInterfaceProfile, used: &[String]) -> String {
    let base = if profile.name.trim().is_empty() {
        profile.profile_id.as_str()
    } else {
        profile.name.trim()
    };
    if !used.iter().any(|name| name == base) {
        return base.to_string();
    }

    let mut candidate = format!("{base} {}", profile.profile_id);
    if !used.iter().any(|name| name == &candidate) {
        return candidate;
    }

    for suffix in 2.. {
        candidate = format!("{base} {suffix}");
        if !used.iter().any(|name| name == &candidate) {
            return candidate;
        }
    }
    unreachable!("unbounded suffix search always returns")
}

fn render_config_with_network_identity(config: &str, identity: &str) -> String {
    let identity_line = format!("network_identity = {identity}");
    let mut output = Vec::new();
    let mut in_reticulum = false;
    let mut inserted = false;

    for line in config.lines() {
        let trimmed = line.trim();
        let starts_section = trimmed.starts_with('[') && trimmed.ends_with(']');
        if starts_section {
            if in_reticulum && !inserted {
                output.push(identity_line.clone());
                inserted = true;
            }
            in_reticulum = trimmed == "[reticulum]";
        }

        if in_reticulum && trimmed.starts_with("network_identity") {
            if !inserted {
                output.push(identity_line.clone());
                inserted = true;
            }
            continue;
        }
        output.push(line.to_string());
    }

    if in_reticulum && !inserted {
        output.push(identity_line);
    }

    format!("{}\n", output.join("\n").trim_end())
}

fn read_reticulum_value(config: &str, expected_key: &str) -> Option<String> {
    let mut in_reticulum = false;
    for line in config.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            in_reticulum = trimmed == "[reticulum]";
            continue;
        }
        if !in_reticulum {
            continue;
        }
        let Some((key, value)) = trimmed.split_once('=') else {
            continue;
        };
        if key.trim() == expected_key {
            let value = value.trim();
            if !value.is_empty() {
                return Some(value.to_string());
            }
        }
    }
    None
}

fn safe_instance_name(value: &str) -> String {
    let sanitized = value
        .trim()
        .chars()
        .filter(|ch| ch.is_ascii_alphanumeric() || *ch == '_' || *ch == '-')
        .collect::<String>();
    if sanitized.is_empty() {
        DEFAULT_INSTANCE_NAME.into()
    } else {
        sanitized
    }
}

fn new_instance_name() -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::sync::atomic::{AtomicU64, Ordering};
    use std::time::{SystemTime, UNIX_EPOCH};

    static COUNTER: AtomicU64 = AtomicU64::new(0);

    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let counter = COUNTER.fetch_add(1, Ordering::Relaxed);
    let mut hasher = DefaultHasher::new();
    nanos.hash(&mut hasher);
    std::process::id().hash(&mut hasher);
    counter.hash(&mut hasher);
    format!(
        "{INSTANCE_NAME_PREFIX}{:06x}",
        hasher.finish() & 0x00ff_ffff
    )
}

fn validate_interface_profiles(payload: &InterfaceProfilesFile) -> AppResult<()> {
    if payload.profiles.len() > INTERFACE_PROFILES_MAX_ITEMS {
        return Err(AppError::Settings(format!(
            "interface profiles exceed the {INTERFACE_PROFILES_MAX_ITEMS} item limit"
        )));
    }
    let mut ids = std::collections::BTreeSet::new();
    for profile in &payload.profiles {
        validate_interface_profile(profile)?;
        if !ids.insert(profile.profile_id.as_str()) {
            return Err(AppError::Settings(
                "interface profiles contain a duplicate profile id".into(),
            ));
        }
    }
    Ok(())
}

fn validate_interface_profile(profile: &ReticulumInterfaceProfile) -> AppResult<()> {
    if profile.peers.len() > INTERFACE_PROFILE_MAX_PEERS {
        return Err(AppError::Settings(format!(
            "interface profile exceeds the {INTERFACE_PROFILE_MAX_PEERS} peer limit"
        )));
    }
    let kind = match &profile.kind {
        InterfaceKind::Unknown(kind) => Some(kind.as_str()),
        _ => None,
    };
    for value in [
        profile.profile_id.as_str(),
        profile.name.as_str(),
        profile.target_host.as_str(),
        profile.network_name.as_str(),
        profile.device_port.as_str(),
    ]
    .into_iter()
    .chain(kind)
    .chain(profile.peers.iter().map(String::as_str))
    {
        validate_interface_scalar(value, INTERFACE_PROFILE_MAX_FIELD_BYTES)?;
    }
    validate_interface_scalar(&profile.passphrase, INTERFACE_PROFILE_MAX_PASSPHRASE_BYTES)?;
    Ok(())
}

fn validate_gateway_presets(payload: &GatewayPresetsFile) -> AppResult<()> {
    if payload.gateways.len() > GATEWAY_PRESETS_MAX_ITEMS {
        return Err(AppError::Settings(format!(
            "gateway presets exceed the {GATEWAY_PRESETS_MAX_ITEMS} item limit"
        )));
    }
    let mut ids = std::collections::BTreeSet::new();
    for gateway in &payload.gateways {
        for value in [
            gateway.id.as_str(),
            gateway.name.as_str(),
            gateway.host.as_str(),
        ] {
            validate_interface_scalar(value, INTERFACE_PROFILE_MAX_FIELD_BYTES)?;
        }
        if !ids.insert(gateway.id.as_str()) {
            return Err(AppError::Settings(
                "gateway presets contain a duplicate id".into(),
            ));
        }
    }
    Ok(())
}

fn validate_interface_scalar(value: &str, max_bytes: usize) -> AppResult<()> {
    if value.len() > max_bytes {
        return Err(AppError::Settings(
            "interface configuration field exceeds its byte limit".into(),
        ));
    }
    if value
        .chars()
        .any(|character| matches!(character, '\r' | '\n' | '\0'))
    {
        return Err(AppError::Settings(
            "interface configuration field contains an unsafe control character".into(),
        ));
    }
    Ok(())
}

fn read_bounded_utf8(path: &Path, max_bytes: u64) -> AppResult<Option<String>> {
    let Some(raw) = read_bounded_regular_file(path, max_bytes)? else {
        return Ok(None);
    };
    String::from_utf8(raw)
        .map(Some)
        .map_err(|_| AppError::Settings(format!("configuration is not UTF-8: {}", path.display())))
}

fn read_bounded_regular_file(path: &Path, max_bytes: u64) -> AppResult<Option<Vec<u8>>> {
    let path_metadata = match std::fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error.into()),
    };
    if !path_metadata.file_type().is_file() {
        return Err(AppError::Settings(format!(
            "configuration path must be a regular file: {}",
            path.display()
        )));
    }
    if path_metadata.len() > max_bytes {
        return Err(AppError::Settings(format!(
            "configuration file exceeds the {max_bytes} byte limit: {}",
            path.display()
        )));
    }
    let file = File::open(path)?;
    let opened_metadata = file.metadata()?;
    if !opened_metadata.is_file() {
        return Err(AppError::Settings(format!(
            "configuration path must open as a regular file: {}",
            path.display()
        )));
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt;
        if path_metadata.dev() != opened_metadata.dev()
            || path_metadata.ino() != opened_metadata.ino()
        {
            return Err(AppError::Settings(format!(
                "configuration path changed while it was being opened: {}",
                path.display()
            )));
        }
    }
    let mut raw = Vec::with_capacity(path_metadata.len() as usize);
    file.take(max_bytes.saturating_add(1))
        .read_to_end(&mut raw)?;
    if raw.len() as u64 > max_bytes {
        return Err(AppError::Settings(format!(
            "configuration file exceeds the {max_bytes} byte limit: {}",
            path.display()
        )));
    }
    Ok(Some(raw))
}

fn write_atomic_private(path: &Path, bytes: &[u8]) -> AppResult<()> {
    write_atomic_private_with(path, bytes, || Ok(()))
}

fn write_atomic_private_with(
    path: &Path,
    bytes: &[u8],
    before_commit: impl FnOnce() -> std::io::Result<()>,
) -> AppResult<()> {
    if bytes.len() as u64 > INTERFACE_PROFILES_MAX_BYTES {
        return Err(AppError::Settings(format!(
            "configuration output exceeds the {INTERFACE_PROFILES_MAX_BYTES} byte limit"
        )));
    }
    let parent = path.parent().ok_or_else(|| {
        std::io::Error::new(ErrorKind::InvalidInput, "configuration path has no parent")
    })?;
    std::fs::create_dir_all(parent)?;
    if !std::fs::symlink_metadata(parent)?.file_type().is_dir() {
        return Err(AppError::Settings(format!(
            "configuration parent must be a directory: {}",
            parent.display()
        )));
    }
    match std::fs::symlink_metadata(path) {
        Ok(metadata) if !metadata.file_type().is_file() => {
            return Err(AppError::Settings(format!(
                "configuration target must be a regular file: {}",
                path.display()
            )));
        }
        Ok(_) => {}
        Err(error) if error.kind() == ErrorKind::NotFound => {}
        Err(error) => return Err(error.into()),
    }
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            std::io::Error::new(
                ErrorKind::InvalidInput,
                "configuration path has no safe filename",
            )
        })?;
    let sequence = INTERFACE_FILE_SEQUENCE.fetch_add(1, Ordering::Relaxed);
    let temporary = parent.join(format!(
        ".{file_name}.{}.{}.interface.tmp",
        std::process::id(),
        sequence
    ));
    let result = (|| -> std::io::Result<()> {
        let mut options = OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            options.mode(0o600);
        }
        let mut file = options.open(&temporary)?;
        file.write_all(bytes)?;
        file.flush()?;
        file.sync_all()?;
        drop(file);
        before_commit()?;
        atomic_replace(&temporary, path)?;
        #[cfg(unix)]
        File::open(parent)?.sync_all()?;
        Ok(())
    })();
    if result.is_err() {
        let _ = std::fs::remove_file(&temporary);
    }
    result.map_err(Into::into)
}

fn new_profile_id() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let millis = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();
    format!("iface_{millis:x}")
}

fn unique_profile_id(existing: &[ReticulumInterfaceProfile]) -> String {
    let base = new_profile_id();
    if !existing.iter().any(|profile| profile.profile_id == base) {
        return base;
    }
    for suffix in 1.. {
        let candidate = format!("{base}_{suffix}");
        if !existing
            .iter()
            .any(|profile| profile.profile_id == candidate)
        {
            return candidate;
        }
    }
    unreachable!("unbounded suffix search always returns")
}

#[cfg(test)]
mod private_file_tests {
    use super::*;
    #[cfg(unix)]
    use std::os::unix::fs::PermissionsExt;

    #[cfg(unix)]
    #[test]
    fn private_atomic_write_repairs_permissive_existing_mode() {
        let path = std::env::temp_dir().join(format!(
            "omenbrowser-private-interface-{}",
            std::process::id()
        ));
        std::fs::write(&path, b"old-secret").expect("seed file");
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644)).expect("seed mode");

        write_atomic_private(&path, b"passphrase = replacement").expect("private rewrite");

        let mode = std::fs::metadata(&path)
            .expect("metadata")
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o600);
        assert_eq!(
            std::fs::read(&path).expect("contents"),
            b"passphrase = replacement"
        );
        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn interface_profile_debug_redacts_passphrase() {
        let mut profile = ReticulumInterfaceProfile::tcp_client("private", "Private Gateway");
        profile.passphrase = "debug-must-not-leak".into();

        let debug = format!("{profile:?}");

        assert!(!debug.contains("debug-must-not-leak"));
        assert!(debug.contains("<redacted>"));
    }

    #[test]
    fn private_replace_fault_preserves_previous_file_and_removes_stage() {
        let root = std::env::temp_dir().join(format!(
            "omenbrowser-private-interface-fault-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).expect("create fixture");
        let path = root.join("interfaces.json");
        std::fs::write(&path, b"previous").expect("seed file");

        let result = write_atomic_private_with(&path, b"replacement", || {
            Err(std::io::Error::other("injected pre-commit failure"))
        });

        assert!(result.is_err());
        assert_eq!(std::fs::read(&path).expect("read prior file"), b"previous");
        assert_eq!(std::fs::read_dir(&root).expect("list fixture").count(), 1);
        let _ = std::fs::remove_dir_all(root);
    }
}
